sonar.projectKey=EsnyE_python-project-52
sonar.organization=esnye

sonar.sources=.
sonar.exclusions=**/migrations/**,**/tests/**,**/__pycache__/**,staticfiles/**,.venv/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11,3.12,3.13,3.14